<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Alternatif;

class AlternatifSeeder extends Seeder
{
    public function run(): void
    {
        $siswa = [
            // Kelas 6A (26 siswa)
            ['nis' => '192001001', 'nama_siswa' => 'Abdulloh Maajid', 'jk' => 'Lk', 'kelas' => '6A'],
            ['nis' => '192001002', 'nama_siswa' => 'Abgha Bhara Nurandana', 'jk' => 'Lk', 'kelas' => '6A'],
            ['nis' => '192001003', 'nama_siswa' => 'Ahmad Faaris', 'jk' => 'Lk', 'kelas' => '6A'],
            ['nis' => '192001004', 'nama_siswa' => 'Alief Al Hafin', 'jk' => 'Lk', 'kelas' => '6A'],
            ['nis' => '192001005', 'nama_siswa' => 'Aqni Ubaidillah Alfaqih', 'jk' => 'Lk', 'kelas' => '6A'],
            ['nis' => '192001006', 'nama_siswa' => 'Averroes Raihan Al \'Afghany', 'jk' => 'Lk', 'kelas' => '6A'],
            ['nis' => '192001007', 'nama_siswa' => 'Fahmi Ahmad Alghifari', 'jk' => 'Lk', 'kelas' => '6A'],
            ['nis' => '192001008', 'nama_siswa' => 'Faiq', 'jk' => 'Lk', 'kelas' => '6A'],
            ['nis' => '192001009', 'nama_siswa' => 'Fathan Aulian Shakil', 'jk' => 'Lk', 'kelas' => '6A'],
            ['nis' => '192001010', 'nama_siswa' => 'Haikal Azmi', 'jk' => 'Lk', 'kelas' => '6A'],
            ['nis' => '192001011', 'nama_siswa' => 'Hasbi Kadavi', 'jk' => 'Lk', 'kelas' => '6A'],
            ['nis' => '202102090', 'nama_siswa' => 'Irfan Tristandi Pratama Putra', 'jk' => 'Lk', 'kelas' => '6A'],
            ['nis' => '192001012', 'nama_siswa' => 'Izzan Abdullah', 'jk' => 'Lk', 'kelas' => '6A'],
            ['nis' => '192001013', 'nama_siswa' => 'Muhammad', 'jk' => 'Lk', 'kelas' => '6A'],
            ['nis' => '192001014', 'nama_siswa' => 'Muhammad Fudhoil', 'jk' => 'Lk', 'kelas' => '6A'],
            ['nis' => '192001015', 'nama_siswa' => 'Muhammad Ravenditya Rachman', 'jk' => 'Lk', 'kelas' => '6A'],
            ['nis' => '212203078', 'nama_siswa' => 'Muhammad Rayyan Aiman', 'jk' => 'Lk', 'kelas' => '6A'],
            ['nis' => '192001016', 'nama_siswa' => 'Muhammad Rayyan Aqilani', 'jk' => 'Lk', 'kelas' => '6A'],
            ['nis' => '192001017', 'nama_siswa' => 'Muhammad Syafiq Miqdad', 'jk' => 'Lk', 'kelas' => '6A'],
            ['nis' => '192001018', 'nama_siswa' => 'Mujahid Asysya\'Bi', 'jk' => 'Lk', 'kelas' => '6A'],
            ['nis' => '192001019', 'nama_siswa' => 'Naufal Zuhdan Yahya', 'jk' => 'Lk', 'kelas' => '6A'],
            ['nis' => '192001020', 'nama_siswa' => 'Qeiz Dzalya Rahadi', 'jk' => 'Lk', 'kelas' => '6A'],
            ['nis' => '192001021', 'nama_siswa' => 'Rafa Fauzan Kamil', 'jk' => 'Lk', 'kelas' => '6A'],
            ['nis' => '192001022', 'nama_siswa' => 'Rizqy Adhyasta Kayana', 'jk' => 'Lk', 'kelas' => '6A'],
            ['nis' => '192001023', 'nama_siswa' => 'Suroikh Abdullah', 'jk' => 'Lk', 'kelas' => '6A'],
            ['nis' => '192001024', 'nama_siswa' => 'Syailendra Putra Ibrohim', 'jk' => 'Lk', 'kelas' => '6A'],
            // Kelas 6B (27 siswa)
            ['nis' => '192001026', 'nama_siswa' => 'Abeer  Amin Bashay', 'jk' => 'Pr', 'kelas' => '6B'],
            ['nis' => '202102090', 'nama_siswa' => 'Almaghaniyya Nadira Bayu', 'jk' => 'Pr', 'kelas' => '6B'],
            ['nis' => '202102091', 'nama_siswa' => 'Alya Zieyska Syakirah', 'jk' => 'Pr', 'kelas' => '6B'],
            ['nis' => '192001027', 'nama_siswa' => 'Aquila Nadya Hafizah', 'jk' => 'Pr', 'kelas' => '6B'],
            ['nis' => '192001028', 'nama_siswa' => 'Atikah Zahidah Al Murobbiyah', 'jk' => 'Pr', 'kelas' => '6B'],
            ['nis' => '192001029', 'nama_siswa' => 'Fathiya Nur Fatihah', 'jk' => 'Pr', 'kelas' => '6B'],
            ['nis' => '192001030', 'nama_siswa' => 'Gelsy Adiva Nayra Achmad', 'jk' => 'Pr', 'kelas' => '6B'],
            ['nis' => '192001032', 'nama_siswa' => 'Hashifah', 'jk' => 'Pr', 'kelas' => '6B'],
            ['nis' => '192001033', 'nama_siswa' => 'Hauro Alifah Husna', 'jk' => 'Pr', 'kelas' => '6B'],
            ['nis' => '192001034', 'nama_siswa' => 'Humayro\' Nazihah', 'jk' => 'Pr', 'kelas' => '6B'],
            ['nis' => '192001035', 'nama_siswa' => 'Husna', 'jk' => 'Pr', 'kelas' => '6B'],
            ['nis' => '192001036', 'nama_siswa' => 'Iffah \'Ainun Rahmah', 'jk' => 'Pr', 'kelas' => '6B'],
            ['nis' => '192001037', 'nama_siswa' => 'Keysha Naiila Putri', 'jk' => 'Pr', 'kelas' => '6B'],
            ['nis' => '192001038', 'nama_siswa' => 'Khansa Salsabila Qurratu\'Ain', 'jk' => 'Pr', 'kelas' => '6B'],
            ['nis' => '192001039', 'nama_siswa' => 'Khayla Maritza Azzahra', 'jk' => 'Pr', 'kelas' => '6B'],
            ['nis' => '192001040', 'nama_siswa' => 'Khunaisah', 'jk' => 'Pr', 'kelas' => '6B'],
            ['nis' => '192001041', 'nama_siswa' => 'Moza Elvina Ramadhani', 'jk' => 'Pr', 'kelas' => '6B'],
            ['nis' => '192001042', 'nama_siswa' => 'Munjiyyah Muttaqien', 'jk' => 'Pr', 'kelas' => '6B'],
            ['nis' => '192001043', 'nama_siswa' => 'Nabilah', 'jk' => 'Pr', 'kelas' => '6B'],
            ['nis' => '192001045', 'nama_siswa' => 'Putri Nur Khoiriah', 'jk' => 'Pr', 'kelas' => '6B'],
            ['nis' => '192001046', 'nama_siswa' => 'Raisya Cettareswara Firnadi', 'jk' => 'Pr', 'kelas' => '6B'],
            ['nis' => '192001047', 'nama_siswa' => 'Shofiyyah Auliaunnisa', 'jk' => 'Pr', 'kelas' => '6B'],
            ['nis' => '192001048', 'nama_siswa' => 'Syaura Ayudia Kinanti', 'jk' => 'Pr', 'kelas' => '6B'],
            ['nis' => '232405106', 'nama_siswa' => 'Vanya Indira Prastika', 'jk' => 'Pr', 'kelas' => '6B'],
            ['nis' => '192001050', 'nama_siswa' => 'Varisha Althaf Bachtiar', 'jk' => 'Pr', 'kelas' => '6B'],
            ['nis' => '192001051', 'nama_siswa' => 'Zahra Al Humairah', 'jk' => 'Pr', 'kelas' => '6B'],
            ['nis' => '192001052', 'nama_siswa' => 'Zainab Laila Ramadhan', 'jk' => 'Pr', 'kelas' => '6B'],
            // Kelas 6C (27 siswa)
            ['nis' => '192001053', 'nama_siswa' => 'Abdul Aziz Iskandar', 'jk' => 'Lk', 'kelas' => '6C'],
            ['nis' => '192001055', 'nama_siswa' => 'Abdurrahman Hisyam', 'jk' => 'Lk', 'kelas' => '6C'],
            ['nis' => '192001122', 'nama_siswa' => 'Abdurrahman Rasyid', 'jk' => 'Lk', 'kelas' => '6C'],
            ['nis' => '192001056', 'nama_siswa' => 'Abrar Amin Bashay', 'jk' => 'Lk', 'kelas' => '6C'],
            ['nis' => '212203077', 'nama_siswa' => 'Akmal Atha Wijaya', 'jk' => 'Lk', 'kelas' => '6C'],
            ['nis' => '192001057', 'nama_siswa' => 'Alifiendra Brata Nugraha', 'jk' => 'Lk', 'kelas' => '6C'],
            ['nis' => '192001058', 'nama_siswa' => 'Daffa Hafizh Argani', 'jk' => 'Lk', 'kelas' => '6C'],
            ['nis' => '192001059', 'nama_siswa' => 'Faisal Emir Rifai', 'jk' => 'Lk', 'kelas' => '6C'],
            ['nis' => '192001060', 'nama_siswa' => 'Fakhri Hamzah Herwanto', 'jk' => 'Lk', 'kelas' => '6C'],
            ['nis' => '192001061', 'nama_siswa' => 'Fawwaz Mubaarok', 'jk' => 'Lk', 'kelas' => '6C'],
            ['nis' => '192001062', 'nama_siswa' => 'Fudhail Al Farruq', 'jk' => 'Lk', 'kelas' => '6C'],
            ['nis' => '192001063', 'nama_siswa' => 'Keanu Marchello Kosta Junior', 'jk' => 'Lk', 'kelas' => '6C'],
            ['nis' => '212203086', 'nama_siswa' => 'Kefian Januar Widi Pramana', 'jk' => 'Lk', 'kelas' => '6C'],
            ['nis' => '192001064', 'nama_siswa' => 'Mas\'Ud', 'jk' => 'Lk', 'kelas' => '6C'],
            ['nis' => '192001065', 'nama_siswa' => 'Muhammad Isa Al-Mahfudz', 'jk' => 'Lk', 'kelas' => '6C'],
            ['nis' => '192001066', 'nama_siswa' => 'Muhammad Riyadh Barraq', 'jk' => 'Lk', 'kelas' => '6C'],
            ['nis' => '192001069', 'nama_siswa' => 'Nurfaqih Dade Ramdhani', 'jk' => 'Lk', 'kelas' => '6C'],
            ['nis' => '192001070', 'nama_siswa' => 'Rabi Bayani El Amien', 'jk' => 'Lk', 'kelas' => '6C'],
            ['nis' => '192001071', 'nama_siswa' => 'Raihan Hanif Sutisna', 'jk' => 'Lk', 'kelas' => '6C'],
            ['nis' => '222304098', 'nama_siswa' => 'Sahl Abdul Haq', 'jk' => 'Lk', 'kelas' => '6C'],
            ['nis' => '192001072', 'nama_siswa' => 'Shafwan Omar Faris', 'jk' => 'Lk', 'kelas' => '6C'],
            ['nis' => '192001073', 'nama_siswa' => 'Sufyan Al-Tsauri', 'jk' => 'Lk', 'kelas' => '6C'],
            ['nis' => '192001074', 'nama_siswa' => 'Suhail', 'jk' => 'Lk', 'kelas' => '6C'],
            ['nis' => '192001075', 'nama_siswa' => 'Tamim', 'jk' => 'Lk', 'kelas' => '6C'],
            ['nis' => '192001076', 'nama_siswa' => 'Teguh Priambada Nugroho', 'jk' => 'Lk', 'kelas' => '6C'],
            ['nis' => '192001077', 'nama_siswa' => 'Wildan Nadly Tsansyabil', 'jk' => 'Lk', 'kelas' => '6C'],
            ['nis' => '232405108', 'nama_siswa' => 'Muhammad', 'jk' => 'Lk', 'kelas' => '6C'],
            // Kelas 6D (29 siswa)
            ['nis' => '192001078', 'nama_siswa' => '\'Aisyah Aqilah', 'jk' => 'Pr', 'kelas' => '6D'],
            ['nis' => '192001080', 'nama_siswa' => 'Azahra Kanaya Ramadhan', 'jk' => 'Pr', 'kelas' => '6D'],
            ['nis' => '232405101', 'nama_siswa' => 'Azkiya Mughni Shaliha', 'jk' => 'Pr', 'kelas' => '6D'],
            ['nis' => '192001081', 'nama_siswa' => 'Fella Fatihah Wirawan', 'jk' => 'Pr', 'kelas' => '6D'],
            ['nis' => '192001082', 'nama_siswa' => 'Fildzah Wienda Ramadhani', 'jk' => 'Pr', 'kelas' => '6D'],
            ['nis' => '192001083', 'nama_siswa' => 'Hawwa', 'jk' => 'Pr', 'kelas' => '6D'],
            ['nis' => '192001084', 'nama_siswa' => 'Kayla Aquila Azzahra', 'jk' => 'Pr', 'kelas' => '6D'],
            ['nis' => '192001085', 'nama_siswa' => 'Keyara Mikaila Mubarok', 'jk' => 'Pr', 'kelas' => '6D'],
            ['nis' => '192001086', 'nama_siswa' => 'Khaira Rizki Althafunnisa', 'jk' => 'Pr', 'kelas' => '6D'],
            ['nis' => '192001087', 'nama_siswa' => 'Khairin Taufiqa Muadzah', 'jk' => 'Pr', 'kelas' => '6D'],
            ['nis' => '202102093', 'nama_siswa' => 'Khairunnisa Aqleen Siceraki', 'jk' => 'Pr', 'kelas' => '6D'],
            ['nis' => '192001088', 'nama_siswa' => 'Khoireen Athirah Zara', 'jk' => 'Pr', 'kelas' => '6D'],
            ['nis' => '192001089', 'nama_siswa' => 'Lubaabah Al Fath', 'jk' => 'Pr', 'kelas' => '6D'],
            ['nis' => '192001090', 'nama_siswa' => 'Maraya Izmaturrahmani', 'jk' => 'Pr', 'kelas' => '6D'],
            ['nis' => '192001091', 'nama_siswa' => 'Medina Rizki Azalia', 'jk' => 'Pr', 'kelas' => '6D'],
            ['nis' => '192001092', 'nama_siswa' => 'Nabila Fauziyah', 'jk' => 'Pr', 'kelas' => '6D'],
            ['nis' => '192001093', 'nama_siswa' => 'Nada Almaira', 'jk' => 'Pr', 'kelas' => '6D'],
            ['nis' => '192001094', 'nama_siswa' => 'Nadhiroh', 'jk' => 'Pr', 'kelas' => '6D'],
            ['nis' => '192001095', 'nama_siswa' => 'Nadiyah Balqis', 'jk' => 'Pr', 'kelas' => '6D'],
            ['nis' => '192001096', 'nama_siswa' => 'Nayla Zanjabila Azzahra', 'jk' => 'Pr', 'kelas' => '6D'],
            ['nis' => '192001097', 'nama_siswa' => 'Raisha Anindya Nurzaman', 'jk' => 'Pr', 'kelas' => '6D'],
            ['nis' => '192001098', 'nama_siswa' => 'Raisya Furqonia Zahira', 'jk' => 'Pr', 'kelas' => '6D'],
            ['nis' => '192001099', 'nama_siswa' => 'Shofa', 'jk' => 'Pr', 'kelas' => '6D'],
            ['nis' => '192001100', 'nama_siswa' => 'Siti Zainab Imaniati', 'jk' => 'Pr', 'kelas' => '6D'],
            ['nis' => '192001101', 'nama_siswa' => 'Suri Aisyah Putri', 'jk' => 'Pr', 'kelas' => '6D'],
            ['nis' => '192001102', 'nama_siswa' => 'Taqiyya Lisaana Aulia', 'jk' => 'Pr', 'kelas' => '6D'],
            ['nis' => '192001104', 'nama_siswa' => 'Zahira Lakeisha Armina', 'jk' => 'Pr', 'kelas' => '6D'],
            ['nis' => '222304099', 'nama_siswa' => 'Zaskia Rahma Syakinah', 'jk' => 'Pr', 'kelas' => '6D'],
            ['nis' => '242506102', 'nama_siswa' => 'Raihanah Zulfa', 'jk' => 'Pr', 'kelas' => '6D'],
        ];

        foreach ($siswa as $s) {
            Alternatif::updateOrCreate(['nis' => $s['nis']], $s);
        }
    }
}
